### ISSUE TITLE
Modal not working

### ISSUE THREAD

**Issue by chrisgeek** [mdbootstrap/Angular-Bootstrap-with-Material-Design#66] opened 2018-03-11 23:28 UTC
I added this code to my angular 5 template file, but nothing happens each time i click the button, i have no idea whats wrong here,navbar and other
 components are working fine
``
    
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
     Launch demo modal
    </button>

    
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                </div>
                <div class="modal-body">
                    ...
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Save changes</button>
                </div>
            </div>
        </div>
    </div>

**Comment by Bloodcast69** [comment] 2018-03-12 06:39
Dear @chrisgeek it seems that you have used a jQUery sample code instead of Angular one.
Please use code from this link and let me know how stuff looks like: 

https://mdbootstrap.com/angular/advanced/modals/

Best Regards,
Damian

**Comment by chrisgeek** [comment] 2018-03-12 07:37
I get this error message when i try the example in the llink

message: "Uncaught (in promise): Error: StaticInjectorError(AppModule)[ModalDirective -> ComponentLoaderFactory]: \n  StaticInjectorError(Platform: core)[ModalDirective -> ComponentLoaderFactory]: \n    NullInjectorError: No provider for ComponentLoaderFactory!\n_NullInjector.prototype.get@webpack-internal:///../../../core/esm5/core.js:1218:19\nresolveToken@webpack-internal:///../../../core/esm5/core.js:1516:17\ntryResolveToken@webpack-internal:///../../../core/esm5/core.js:1458:16\nStaticInjector.prototype.get@webpack-internal:///../../../core/esm5/core.js:1326:20\nresolveToken@webpack-internal:///../../../core/esm5/core.js:1516:17\ntryResolveToken@webpack-internal:///../../../core/esm5/core.js:1458:16\nStaticInjector.prototype.get@webpack-internal:///../../../core/esm5/core.js:1326:20\nresolveNgModuleDep@webpack-internal:///../../../core/esm5/core.js:11070:12\nNgModuleRef_.prototype.get@webpack-internal:///../../../core/esm5/core.js:12303:16\nresolveDep@webpack-internal:///../../../core/esm5/core.js:12793…"

**Comment by Bloodcast69** [comment] 2018-03-12 07:39
Could you show me your app.module.ts file?

**Comment by chrisgeek** [comment] 2018-03-12 07:40
import { BrowserModule } from '@angular/platform-browser';
import { NgModule, NO_ERRORS_SCHEMA } from '@angular/core';
import {MDBBootstrapModule} from 'angular-bootstrap-md';
//import { ModalDirective } from "angular-bootstrap-md";
import { HomeComponent } from "./home/home.component";
import { AppRoutingModule } from "./app-routing/app-routing.module";


import { AppComponent } from './app.component';


@NgModule({
  declarations: [
    AppComponent,
    HomeComponent
  ],
  imports: [
    BrowserModule,
    MDBBootstrapModule,
    AppRoutingModule
  ],
 // schemas:[NO_ERRORS_SCHEMA],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }

**Comment by Bloodcast69** [comment] 2018-03-12 07:45
You don't have to import any things from modal to use them. Please remove that ModalDirective import, and uncomment schemas array. I hope that import {BrowserModule} and import {ngModule, NO_ERRORS_SCHEMA} in your file got the proper path like: '@angular/core' and other.

**Comment by chrisgeek** [comment] 2018-03-12 07:52
The error is still the same, could it be that MDB is not compatible with all versions of angular?, am running angular 5

**Comment by Bloodcast69** [comment] 2018-03-12 08:17
MDB is compatible with Angular 5.0.0 - 5.2.6 versions. Please show me your app.component.ts file

**Comment by chrisgeek** [comment] 2018-03-12 08:21
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'app';
}

**Comment by Bloodcast69** [comment] 2018-03-12 08:24
Could you please send me your project at d.gemza@mdbootstrap.com ? I'll take a look at your files and look for problem.

**Comment by chrisgeek** [comment] 2018-03-12 08:27
How about i send you the github repo link, the folder size is quite big 50mb, gmail won't permit sending such file.

**Comment by Bloodcast69** [comment] 2018-03-12 08:28
Okey, no problem. Send me github link

**Comment by chrisgeek** [comment] 2018-03-12 18:32
https://github.com/chrisgeek/kliqital...its a rails 5 API app, so the angular files are in the client folder

**Comment by chrisgeek** [comment] 2018-03-12 19:56
Adding this to imports on app-module did the trick, MDBBootstrapModule.forRoot().  its working fine now.

**Comment by Bloodcast69** [comment] 2018-03-13 06:58
So everything is okay right now. Closing this ticket.
Best Regards,
Damian

**Closed by Bloodcast69** 2018-03-13 06:58 UTC

**Comment by mandy218** [comment] 2018-07-12 07:02
I am facing the same issue can you send me the solution

**Comment by Bloodcast69** [comment] 2018-07-13 05:56
Dear @mandy218 ,
Please provide me more informations about your problem, or reproduction example or I won't be able to help you.

**Comment by igorroman777** [comment] 2018-09-07 18:14
Hi, I work with angular 6.1.0, I have everything installed but the component MDBBootstrapModule , but e.g. <mdb-navbar> does not work: it is not shown properly.

**Comment by 13garthbaker** [comment] 2019-09-08 21:58
thank you so much dude!! :D 1st time worked and the home documentation doesn't even work lol.
