### ISSUE TITLE
Bug: Click on the label is triggering another input

### ISSUE THREAD

**Issue by SiddharthaSarma** [mdbootstrap/Angular-Bootstrap-with-Material-Design#61] opened 2018-02-28 06:38 UTC
In the [demo site](https://mdbootstrap.com/angular/components/) under the inputs section we can see **Error or Success Messages** another sub-section. There is one set of email and password fields on top of this section and one more set below the sub-section.

I don't think there is no need of  two set of inputs(email and password) one above and one below the sub-heading. If it is done intentionally, then if we click on the second set of inputs (email and password) labels then first set inputs(which is on the top) are triggering.

I think may be that is not the required functionality.

**Comment by Bloodcast69** [comment] 2018-02-28 06:41
Hello SiddharthaSarma,
Your problem is caused by this: If we got more than 1 input and more than 1 label with the same id / for attribute, the browser doesn't know, which input we want to activate. Please change ID of the second input, and for attribute on second input's label. 
This should help you. If not, let me know.
Best Regards,
Damian

**Comment by Bloodcast69** [comment] 2018-02-28 07:24
Dear @SiddharthaSarma why do you need something like demo site git repo? We haven't got something like this. Every information that you need is placed in our documentation: https://mdbootstrap.com/angular

This demo site: https://mdbootstrap.com/angular/components/ is no longer in use, it's an old-time relic, so things showed there could be outdated.

Only one place where you can obtain information how to use our components, is our docs.
Best Regards,
Damian

**Comment by SiddharthaSarma** [comment] 2018-02-28 07:31
I am just checking the live demo of the angular mdbootstrap. Sorry, I don't know that was the outdated site. 
Thanks, I will check the docs :).

**Comment by Bloodcast69** [comment] 2018-02-28 07:32
So if everything is clear, I'm closing this ticket.
Best Regards,
Damian

**Closed by Bloodcast69** 2018-02-28 07:32 UTC
