### ISSUE TITLE
TypeError: Cannot read property 'kind' of undefined

### ISSUE THREAD

**Issue by danielsogl** [mdbootstrap/Angular-Bootstrap-with-Material-Design#29] opened 2017-11-20 18:01 UTC
Since im using the md-bootstrap module in my project, I can't build my app in prod mode.

If I build it with `ng build --prod` im getting this error:

```
ERROR in Error: TypeError: Cannot read property 'kind' of undefined
at nodeCanBeDecorated (/Users/danielsogl/Documents/DHBW Projekt 2017/dhbw-projekt-app/node_modules/typescript/lib/typescript.js:7805:36)
    at nodeIsDecorated (/Users/danielsogl/Documents/DHBW Projekt 2017/dhbw-projekt-app/node_modules/typescript/lib/typescript.js:7825:16)
    at nodeOrChildIsDecorated (/Users/danielsogl/Documents/DHBW Projekt 2017/dhbw-projekt-app/node_modules/typescript/lib/typescript.js:7829:16)
    at Object.forEach (/Users/danielsogl/Documents/DHBW Projekt 2017/dhbw-projekt-app/node_modules/typescript/lib/typescript.js:1506:30)
    at Object.childIsDecorated (/Users/danielsogl/Documents/DHBW Projekt 2017/dhbw-projekt-app/node_modules/typescript/lib/typescript.js:7835:27)
    at getClassFacts (/Users/danielsogl/Documents/DHBW Projekt 2017/dhbw-projekt-app/node_modules/typescript/lib/typescript.js:51088:20)
    at visitClassDeclaration (/Users/danielsogl/Documents/DHBW Projekt 2017/dhbw-projekt-app/node_modules/typescript/lib/typescript.js:51113:25)
    at visitTypeScript (/Users/danielsogl/Documents/DHBW Projekt 2017/dhbw-projekt-app/node_modules/typescript/lib/typescript.js:50972:28)
    at visitorWorker (/Users/danielsogl/Documents/DHBW Projekt 2017/dhbw-projekt-app/node_modules/typescript/lib/typescript.js:50785:24)
    at sourceElementVisitorWorker (/Users/danielsogl/Documents/DHBW Projekt 2017/dhbw-projekt-app/node_modules/typescript/lib/typescript.js:50817:28)
    at saveStateAndInvoke (/Users/danielsogl/Documents/DHBW Projekt 2017/dhbw-projekt-app/node_modules/typescript/lib/typescript.js:50738:27)
    at sourceElementVisitor (/Users/danielsogl/Documents/DHBW Projekt 2017/dhbw-projekt-app/node_modules/typescript/lib/typescript.js:50799:20)
    at visitNodes (/Users/danielsogl/Documents/DHBW Projekt 2017/dhbw-projekt-app/node_modules/typescript/lib/typescript.js:49280:48)
    at Object.visitLexicalEnvironment (/Users/danielsogl/Documents/DHBW Projekt 2017/dhbw-projekt-app/node_modules/typescript/lib/typescript.js:49313:22)
    at visitSourceFile (/Users/danielsogl/Documents/DHBW Projekt 2017/dhbw-projekt-app/node_modules/typescript/lib/typescript.js:51059:53)
    at saveStateAndInvoke (/Users/danielsogl/Documents/DHBW Projekt 2017/dhbw-projekt-app/node_modules/typescript/lib/typescript.js:50738:27)
```

I'm using the latest release and Angular 5.0.2

**Comment by mdbootstrap** [comment] 2017-11-20 22:45
Dear Daniel, 
as you can notice it looks like an issue related to typescript. 
Could you please share your project/code with us so we could analyse it? Please also provide us more information about the environment, os, Angular, CLI, TS versions etc.

**Comment by vadhavkar** [comment] 2017-11-21 13:40
Looks like the problem is with the "@OnChange" decorator used in Tooltip directive. If I comment it out in tooltip.directive.ts I dont get that error.

- Asit

**Comment by danielsogl** [comment] 2017-11-21 18:58
I'm facing this issue since I also upgraded my Angular CLI to 1.5.2 so I downgraded to 1.5 and it worked.

I found this issue in the Angular-CLI repo: https://github.com/angular/angular-cli/issues/8434#issuecomment-346005112

**Comment by frankguns** [comment] 2017-12-07 21:44
Same problem here. I also got it working by commenting out @onchange in tooltip.directive.ts

**Comment by Bloodcast69** [comment] 2017-12-22 06:21
Hey Guys,

I’ve checked this case, and found a fix for that. It’s problem with Typescript. I think, that it will be fixed in next TypeScript releases, but for now you can try to use solution of user ‘gmavritsakis’ added on GitHub: https://github.com/angular/angular-cli/issues/8434 .

In file ‘typescript.js’ located in: node_modules/typescript/lib

Replace all the function
function nodeCanBeDecorated(node)
with the following code:

`function nodeCanBeDecorated(node) {
       switch (node.kind) {
           case 229 /* ClassDeclaration */:
               // classes are valid targets
               return true;
           case 149 /* PropertyDeclaration */:
               // property declarations are valid if their parent is a class declaration.
   			// return node.parent.kind === 229 /* ClassDeclaration */;
   			return (node.parent && node.parent.kind === 229) || (node.original && node.original.parent && node.original.parent.kind === 229);
           case 153 /* GetAccessor */:
           case 154 /* SetAccessor */:
           case 151 /* MethodDeclaration */:
               // if this method has a body and its parent is a class declaration, this is a valid target.
               return node.body !== undefined &&
   				// && node.parent.kind === 229 /* ClassDeclaration */;
   				(node.parent && node.parent.kind === 229) || (node.original && node.original.parent && node.original.parent.kind === 229);
           case 146 /* Parameter */:
               // if the parameter's parent has a body and its grandparent is a class declaration, this is a valid target;
               // return node.parent.body !== undefined
               //     && (node.parent.kind === 152 /* Constructor */
               //         || node.parent.kind === 151 /* MethodDeclaration */
               //         || node.parent.kind === 154 /* SetAccessor */)
   			//     && node.parent.parent.kind === 229 /* ClassDeclaration */;
   			
   			var parent = node.parent || (node.original && node.original.parent);
   			return parent && parent.body !== undefined &&
                     (parent.kind === 152
                        || parent.kind === 151
                        || parent.kind === 154) && parent.parent.kind === 229;
       }
       return false;
   }`

**Closed** 2018-01-02 10:40 UTC

**Comment by jhourlad** [comment] 2018-03-02 16:37
My eyes were burnt looking at the code formatting.
