### ISSUE TITLE
Webpack failed to compile

### ISSUE THREAD

**Issue by cmckni3** [mdbootstrap/Angular-Bootstrap-with-Material-Design#23] opened 2017-11-06 15:59 UTC
```
ERROR in ./node_modules/angular-bootstrap-md/index.ts
Module build failed: Error: <PROJECT_PATH>/node_modules/angular-bootstrap-md/index.ts is not part of the compilation output. Please check the other error messages for details.
    at AngularCompilerPlugin.getCompiledFile (<PROJECT_PATH>/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:629:23)
    at plugin.done.then (<PROJECT_PATH>/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 @ ./src/app/modules/shared/shared.module.ts 10:0-58
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts
```

Using Angular CLI 1.5.0 and Angular 5.0.0

**Comment by Korben11** [comment] 2017-11-08 10:20
Hi, have you found the solution? Thanks!

**Comment by DuncanLewis** [comment] 2017-11-08 12:07
Experiencing this issue too.

**Comment by oxxa** [comment] 2017-11-08 13:02
I found this cli issue  [#8284](https://github.com/angular/angular-cli/issues/8284).  I set my tsconfig.app.json to add this and it seems to fix things (though I am just evaluating this project so I have no real-world/complex app to test with so ymmv).

`
  "include": [
    "**/*.ts",
    "../node_modules/angular-bootstrap-md/index.ts"
  ],
`

**Comment by mdbootstrap** [comment] 2017-11-08 15:39
Indeed, if you try to use it with Angular 5 it will throw this error which is caused by issue quoted by @oxxa . The workaround is to either use: 

> "include": [ "**/*.ts", "../node_modules/angular-bootstrap-md/index.ts" ],

or

> ng serve --prod

**Comment by mmanavaz** [comment] 2017-11-08 15:55
+1 I am experiencing this issue as well.

 Tried the workaround (adding the index.ts file in "includes") but was getting another error-
 Error: error TS18003: No inputs were found in config file 'tsconfig.json'. Specified 'include' paths were '["node_modules/datatable/index.ts","node_modules/typeahead/index.ts"]' and 'exclude' paths were '["test.ts","**/*.spec.ts"]'.

**Comment by oxxa** [comment] 2017-11-08 16:08
@mmanavaz  for reference here is my whole tsconfig.app.json (not tsconfig.json) although @mdbootstrap solution of the --prod flag would seem the easier option.
```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "baseUrl": "./",
    "module": "es2015",
    "types": []
  },
  "include": [
    "**/*.ts",
    "../node_modules/angular-bootstrap-md/index.ts"
  ],
  "exclude": [
    "test.ts",
    "**/*.spec.ts"
  ]
}
```

**Comment by camow7** [comment] 2017-11-12 22:59
When running `ng serve -prod` I get the following error:

> ERROR in Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exp
orted function (position 194:50 in the original .ts file), resolving symbol NgModule in C:/SAPHI/Projects/prueandcam/node_modules/ng-mdb-pro/node_modules/@angular/core/core
.d.ts, resolving symbol MDBRootModules in C:/SAPHI/Projects/prueandcam/node_modules/ng-mdb-pro/mdb.module.ts, resolving symbol MDBRootModules in C:/SAPHI/Projects/prueandca
m/node_modules/ng-mdb-pro/mdb.module.ts

>

**Comment by mmanavaz** [comment] 2017-11-12 23:12
I was able to fix my issue. Unfortunately I do not remember exactly how I fixed it as it has been a few days. Make sure the right files are included in tsconfig.ts.

**Comment by camow7** [comment] 2017-11-24 11:51
After updating to Angular 5 I now get this error:

> ERROR in node_modules/ng-mdb-pro/free/dropdown/dropdown.directive.ts(156,31): error TS2345: Argument of type 'Subscription' is not assignable to parameter of type 'Subscription'.
  Property '_parent' is protected but type 'Subscription' is not a class derived from 'Subscription'.
node_modules/ng-mdb-pro/pro/autocomplete/services/remote-data.service.ts(79,8): error TS2339: Property 'catch' does not exist on type 'Observable<CompleterItem[]>'.
node_modules/ng-mdb-pro/pro/smoothscroll/mdb-page-scroll.directive.ts(133,48): error TS2352: Type 'Subscription' cannot be converted to type 'Subscription'.
  Property '_parent' is protected but type 'Subscription' is not a class derived from 'Subscription'.

**Comment by embryologist** [comment] 2017-12-03 22:12
same issue here

**Comment by camow7** [comment] 2017-12-05 20:59
I solved the issue by updating rxjs:

1. `npm uninstall rxjs`
2. `npm install rxjs -g`
3. `rm -rf node_modules`
4. `npm install`

**Comment by santhoshnv** [comment] 2018-01-01 11:17
I got the error as 

Error: error TS18003: No inputs were found in config file 'tsconfig.json'. Specified 'include' paths were '["node_modules/angular-bootstrap-md/**/*.ts","src/**/*.ts"]' and 'exclude' paths were '["test.ts","**/*.spec.ts"]'.


My **tsconfig.json** file is
```

{
  "compileOnSave": false,
  **// "include": ["node_modules/angular-bootstrap-md/**/*.ts",  "src/**/*.ts"],**
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "baseUrl": "src",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2016",
      "dom"
    ]
  }
}

```
I tried to add the include statement in highlighted space.

**Comment by cmckni3** [comment] 2018-01-01 22:12
That should be correct @santhoshnv. My `tsconfig.json` is below

```
{
  "compileOnSave": false,
  "include": ["node_modules/angular-bootstrap-md/**/*.ts",  "src/**/*.ts"],
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  }
}
```

**Comment by santhoshnv** [comment] 2018-01-02 16:59
Thanks @cmckni3 now is working fine

**Comment by andrespinzon** [comment] 2018-01-07 01:05
I got same issue only slightly different scenario. I can develop/test my module, however I need to package that up and publish it to npm. 

I'm using ng-packagr which runs mostly fine except for a warning about ng-mdb-pro being imported but can't be resolved so it treats it as an external dependency. 

The packager goes on to do its thing, but due to mdb, it misses a whole bunch of file (components, services). I do some manipulation to get those file in my package and publish it to npm.  However when when using that library in another project it comes back with  the "index.ts is not part of the compilation" error.  

Note that my "host" project has got the  
`"include": ["node_modules/angular-bootstrap-md/**/*.ts",  "src/**/*.ts"],`

Has anybody attempted to package a module that uses MDB?

**Comment by cmckni3** [comment] 2018-01-07 02:15
I tried but couldn't get past a compilation error in the dropdown module. See #24. @andrespinzon can you make a PR that uses ng-packagr? I found out about it recently but stopped using MD Bootstrap due to this issue and the Sass compilation issue.

**Comment by mdbootstrap** [comment] 2018-01-10 12:58
Chris, we are working on compiling MDB to JS. Feel free to participate along us, if you want we can add you to our Beta Tester slack channel. Please contact us at office@mdbootstrap.com and I will send you an invite. Other users are also welcome.

**Comment by chegola** [comment] 2018-01-10 15:20
I am in searching out UI to use in my project and really like MDB angular because I am using  [Jhipster](https://github.com/jhipster/generator-jhipster) with sass option and also it uses webpack. Now I got the same issue of webpack complilation. I have not much experienced in web-front-end that's why I am choosing MDB. Hopefully MDB angular support webpack in soon.

**Comment by cmckni3** [comment] 2018-01-10 18:36
@mdbootstrap sent an email about Slack access.

**Comment by mdbootstrap** [comment] 2018-01-11 15:40
@cmckni3 didn't get any email :( please try direct email d.adach@mdbootstrap.com or ping me on twitter: https://twitter.com/dawidadach

**Comment by MrAndersonDG** [comment] 2018-01-15 01:20
i have save same issue

**Closed** 2018-02-20 19:03 UTC

**Comment by mrpatel15** [comment] 2018-05-16 04:08
ERROR in ./node_modules/angular-bootstrap-md/index.ts
Module build failed: Error: /Users/mqs618/workspace/fs-tool/fs/fs-app/node_modules/angular-bootstrap-md/index.ts is missing from the
TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged libr
ary. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package
 Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/Users/mqs618/workspace/fs-tool/fs/fs-app/node_modules/@ngtools/webpack/src/angular_com
piler_plugin.js:709:23)
    at plugin.done.then (/Users/mqs618/workspace/fs-tool/fs/fs-app/node_modules/@ngtools/webpack/src/loader.js:41:31)
    at <anonymous>

    at process._tickCallback (internal/process/next_tick.js:188:7)
ERROR in multi ./styles.scss ./node_modules/font-awesome/scss/font-awesome.scss ./node_modules/bootstrap/scss/bootstrap.scss ./node_m

**Comment by mrpatel15** [comment] 2018-05-16 04:10
same issues, added below dependency but still not woeking

// tsconfig.json
{
  "compileOnSave": false,
  "include": [ "**/*.ts", "../node_modules/angular-bootstrap-md/index.ts" ],
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  }
}

/// tsconfig.app.json

{
  "extends": "../tsconfig.json",
  "include": [
    "**/*.ts",
     "../node_modules/angular-bootstrap-md/index.ts"
  ],
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "baseUrl": "./",
    "module": "es2015",
    "types": []
  },
  "exclude": [
    "test.ts",
    "**/*.spec.ts"
  ]
}

**Comment by keithoys** [comment] 2018-05-16 08:42
I'm using using Angular 6.0.1 and am getting the same error too:
`index.ts is missing from the TypeScript compilation`

**Comment by Bloodcast69** [comment] 2018-05-16 10:13
@mrpatel15 please note, that you're having a logic mistake in your "inlude" in tsconfig.json file.

tsconfig.json is located in root directory of your app, so if you're including angular-bootstrap-md package from node_modules directory, your "include" should look like below:

`"include": ["node_modules/angular-bootstrap-md/**/*.ts",  "src/**/*.ts"], `

If this include won't work to you, please try to change order or "src" with "node_modules", so it then 
should looks like below:

`"include": ["src/**/*.ts", "node_modules/angular-bootstrap-md/**/*.ts"], `

Also you don't need to add "include" in your tsconfig.app.json file, because this file extends from root tsconfig.json.

@keithoys please remove "include" line from your tsconfig.app.json file and try one more time.

Guys, if my advices won't help you, please let me know.

**Comment by ArunEdathadan** [comment] 2019-06-27 07:57
> "include": ["node_modules/angular-bootstrap-md/**/*.ts",  "src/**/*.ts"],

reinstalling mdb fixed my issue
